# Generated by Django 3.1.3 on 2020-11-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bidder_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
